name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  cabal-build:
    strategy:
      matrix:
        ghc-version:
          - "8.4.4"
          - "8.6.5"
          - "8.8.4"
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.8"
          - "9.6.7"
          - "9.8.4"
          - "9.10.2"
          - "9.12.2"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        cabal-version: "3.4"
        ghc-version: ${{ matrix.ghc-version }}
    - name: Cache
      uses: actions/cache@v4
      id: cache-dot-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc-version }}
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
